Generate username function now being used in OAuth flow
potatolondon/djangae pull request #1262
Opened 2020-10-19 13:15 UTC by purvitrivedi

Fixes #[include a number of issue this PR is fixing].

Summary of changes proposed in this Pull Request:
- `_generate_unused_username` now being used in `oauth2.py`
- Profile object does not contain username - only userId, full name, given name, family name, image URL and email, so we won't create add char field `profile_username` to `AbstractGoogleUser`

PR checklist: 
- [ ] Added tests for my change

2020-10-19 15:28 UTC, Kazade requested changes

2020-10-19 15:28 UTC, Kazade commented on djangae/contrib/googleauth/backends/oauth2.py
> +from .iap import _generate_unused_username
Could you move the `_generate_unused_username` function into `backends/__init__.py` and then import from there in both iap.py and here? (e.g. `from . import _generate_unused_username`)

2020-10-19 15:41 UTC, purvitrivedi commented on djangae/contrib/googleauth/backends/oauth2.py
> +from .iap import _generate_unused_username
Done!

2020-10-21 13:15 UTC, merged

2020-11-23 10:21 UTC, flea89 commented
Fixed by https://github.com/potatolondon/djangae/pull/1262