1268 gae versions
potatolondon/djangae pull request #1269
Opened 2020-10-27 08:55 UTC by flea89

Fixes #[include a number of issue this PR is fixing].

Summary of changes proposed in this Pull Request:
- 
- 
- 

PR checklist:
- [ ] Updated relevant documentation
- [ ] Updated CHANGELOG.md 
- [ ] Added tests for my change

2020-11-02 15:12 UTC, sleepyjames requested changes
Nice one. Can you document the use of `OAUTH2_REDIRECT_URL` too please.

2020-11-02 15:12 UTC, sleepyjames commented on djangae/contrib/googleauth/views.py
> +    url = OAUTH2_REDIRECT_URL if OAUTH2_REDIRECT_URL else original_url
```suggestion
    url = OAUTH2_REDIRECT_URL or original_url
```

2020-11-02 17:06 UTC, flea89 commented on djangae/contrib/googleauth/views.py
> +OAUTH2_REDIRECT_URL = getattr(settings, 'OAUTH2_REDIRECT_URL', None)
Moved, thanks!

2020-11-03 09:28 UTC, flea89 commented on djangae/contrib/googleauth/tests/test_oauth.py
> +            self.assertTrue(auth_url.calls[0].kwargs.items() > {
sure

2020-11-03 09:30 UTC, flea89 commented
Thanks for the feedback @sleepyjames , actioned everything and pushed some tests as well.

2020-11-03 09:52 UTC, sleepyjames commented
Great, thanks @flea89

2020-11-03 14:52 UTC, sleepyjames approved these changes

2020-11-03 14:52 UTC, sleepyjames commented on docs/googleauth.md
> +required to configure a list of Authorised domains and Oauth redirects.
```suggestion
required to configure a list of Authorised domains and OAuth redirects.
```

2020-11-03 16:22 UTC, merged